version: "3.8"
services:
  development:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    working_dir: /workspace
    network_mode: host
    init: true
    volumes:
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker-host.sock
      - go-cache:/root/go
    environment:
      - DOCKER_HOST=unix:///var/run/docker-host.sock
      - PGPASSFILE=/workspace/question_3/.pgpass"

    command: /bin/sh -c "while sleep 1000; do :; done"
#
# Source:
# https://github.com/microsoft/vscode-dev-containers/blob/main/containers/docker-existing-docker-compose/.devcontainer/docker-compose.yml

volumes:
  go-cache:
